# Docker Compose configuration for Celery services
# Sistema de Polinización y Germinación

version: '3.8'

services:
  # Redis service for Celery broker and result backend
  redis:
    image: redis:7-alpine
    container_name: sistema_polinizacion_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Celery Worker
  celery_worker:
    build: .
    container_name: sistema_polinizacion_celery_worker
    command: celery -A sistema_polinizacion worker --loglevel=info --concurrency=4
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./media:/app/media
    environment:
      - DJANGO_SETTINGS_MODULE=sistema_polinizacion.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "celery", "-A", "sistema_polinizacion", "inspect", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Celery Beat (Scheduler)
  celery_beat:
    build: .
    container_name: sistema_polinizacion_celery_beat
    command: celery -A sistema_polinizacion beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
      - ./logs:/app/logs
    environment:
      - DJANGO_SETTINGS_MODULE=sistema_polinizacion.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy
      celery_worker:
        condition: service_healthy
    restart: unless-stopped

  # Celery Flower (Monitoring)
  celery_flower:
    build: .
    container_name: sistema_polinizacion_celery_flower
    command: celery -A sistema_polinizacion flower --port=5555
    ports:
      - "5555:5555"
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=sistema_polinizacion.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - FLOWER_BASIC_AUTH=admin:admin123  # Change in production
    depends_on:
      redis:
        condition: service_healthy
      celery_worker:
        condition: service_healthy
    restart: unless-stopped

volumes:
  redis_data:
    driver: local

networks:
  default:
    name: sistema_polinizacion_network