# Generated by Django 4.2.7 on 2025-10-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClimateCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha de creación del registro"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Fecha de última actualización del registro",
                    ),
                ),
                (
                    "climate",
                    models.CharField(
                        choices=[
                            ("I", "Intermedio"),
                            ("W", "Caliente"),
                            ("C", "Frío"),
                            ("IW", "Intermedio Caliente"),
                            ("IC", "Intermedio Frío"),
                        ],
                        help_text="Tipo de clima",
                        max_length=2,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Observaciones adicionales sobre las condiciones climáticas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Condición Climática",
                "verbose_name_plural": "Condiciones Climáticas",
                "ordering": ["-created_at"],
            },
        ),
    ]
