# Generated by Django 4.2.7 on 2025-09-27 06:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pollination", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GerminationCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha de creación del registro"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Fecha de última actualización del registro",
                    ),
                ),
                (
                    "climate",
                    models.CharField(
                        choices=[
                            ("Controlado", "Ambiente controlado"),
                            ("Invernadero", "Invernadero"),
                            ("Exterior", "Exterior"),
                            ("Laboratorio", "Laboratorio"),
                        ],
                        help_text="Tipo de ambiente climático",
                        max_length=50,
                    ),
                ),
                (
                    "substrate",
                    models.CharField(
                        choices=[
                            ("Turba", "Turba"),
                            ("Perlita", "Perlita"),
                            ("Vermiculita", "Vermiculita"),
                            ("Corteza de pino", "Corteza de pino"),
                            ("Musgo sphagnum", "Musgo sphagnum"),
                            ("Mezcla personalizada", "Mezcla personalizada"),
                        ],
                        help_text="Tipo de sustrato utilizado",
                        max_length=50,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Ubicación específica (vivero, mesa, etc.)",
                        max_length=200,
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Temperatura promedio en grados Celsius",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "humidity",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Humedad relativa en porcentaje (0-100)",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "light_hours",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Horas de luz diarias",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "substrate_details",
                    models.TextField(
                        blank=True,
                        help_text="Detalles adicionales sobre el sustrato (proporciones, preparación, etc.)",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Observaciones adicionales sobre las condiciones",
                    ),
                ),
            ],
            options={
                "verbose_name": "Condición de Germinación",
                "verbose_name_plural": "Condiciones de Germinación",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SeedSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha de creación del registro"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Fecha de última actualización del registro",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre descriptivo de la fuente de semillas",
                        max_length=100,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("Autopolinización", "Autopolinización"),
                            ("Sibling", "Polinización entre hermanos"),
                            ("Híbrido", "Hibridación"),
                            ("Otra fuente", "Otra fuente externa"),
                        ],
                        help_text="Tipo de procedencia de las semillas",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Descripción detallada de la fuente"
                    ),
                ),
                (
                    "external_supplier",
                    models.CharField(
                        blank=True,
                        help_text="Proveedor externo de semillas (si aplica)",
                        max_length=200,
                    ),
                ),
                (
                    "collection_date",
                    models.DateField(
                        blank=True,
                        help_text="Fecha de recolección de las semillas",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si la fuente está activa en el sistema",
                    ),
                ),
                (
                    "pollination_record",
                    models.ForeignKey(
                        blank=True,
                        help_text="Registro de polinización de origen (si aplica)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="seed_sources",
                        to="pollination.pollinationrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fuente de Semillas",
                "verbose_name_plural": "Fuentes de Semillas",
                "ordering": ["name", "source_type"],
            },
        ),
        migrations.CreateModel(
            name="GerminationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha de creación del registro"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Fecha de última actualización del registro",
                    ),
                ),
                (
                    "germination_date",
                    models.DateField(
                        help_text="Fecha en que se realizó la siembra/germinación"
                    ),
                ),
                (
                    "estimated_transplant_date",
                    models.DateField(
                        blank=True,
                        help_text="Fecha estimada de trasplante (calculada automáticamente)",
                        null=True,
                    ),
                ),
                (
                    "seeds_planted",
                    models.PositiveIntegerField(
                        help_text="Cantidad de semillas sembradas",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "seedlings_germinated",
                    models.PositiveIntegerField(
                        default=0, help_text="Cantidad de plántulas que germinaron"
                    ),
                ),
                (
                    "transplant_days",
                    models.PositiveIntegerField(
                        default=90,
                        help_text="Días estimados para trasplante según la especie",
                    ),
                ),
                (
                    "is_successful",
                    models.BooleanField(
                        blank=True,
                        help_text="Indica si la germinación fue exitosa",
                        null=True,
                    ),
                ),
                (
                    "transplant_confirmed",
                    models.BooleanField(
                        default=False, help_text="Indica si se confirmó el trasplante"
                    ),
                ),
                (
                    "transplant_confirmed_date",
                    models.DateField(
                        blank=True,
                        help_text="Fecha en que se confirmó el trasplante",
                        null=True,
                    ),
                ),
                (
                    "observations",
                    models.TextField(
                        blank=True,
                        help_text="Observaciones adicionales sobre la germinación",
                    ),
                ),
                (
                    "germination_condition",
                    models.ForeignKey(
                        help_text="Condiciones ambientales de germinación",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="germination_records",
                        to="germination.germinationcondition",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        help_text="Planta/especie que se está germinando",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="germination_records",
                        to="pollination.plant",
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        help_text="Usuario responsable de la germinación",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="germination_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seed_source",
                    models.ForeignKey(
                        help_text="Fuente de las semillas utilizadas",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="germination_records",
                        to="germination.seedsource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Germinación",
                "verbose_name_plural": "Registros de Germinación",
                "ordering": ["-germination_date", "-created_at"],
            },
        ),
    ]
