# Generated by Django 4.2.7 on 2025-10-20 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("germination", "0002_update_germination_condition_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="GerminationSetup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha de creación del registro"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Fecha de última actualización del registro",
                    ),
                ),
                (
                    "substrate",
                    models.CharField(
                        choices=[
                            ("Turba", "Turba"),
                            ("Perlita", "Perlita"),
                            ("Vermiculita", "Vermiculita"),
                            ("Corteza de pino", "Corteza de pino"),
                            ("Musgo sphagnum", "Musgo sphagnum"),
                            ("Mezcla personalizada", "Mezcla personalizada"),
                        ],
                        help_text="Tipo de sustrato utilizado",
                        max_length=50,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Ubicación específica (vivero, mesa, etc.)",
                        max_length=200,
                    ),
                ),
                (
                    "substrate_details",
                    models.TextField(
                        blank=True,
                        help_text="Detalles adicionales sobre el sustrato (proporciones, preparación, etc.)",
                    ),
                ),
                (
                    "setup_notes",
                    models.TextField(
                        blank=True,
                        help_text="Observaciones adicionales sobre la configuración de germinación",
                    ),
                ),
                (
                    "climate_condition",
                    models.ForeignKey(
                        help_text="Condición climática para la germinación",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="germination_setups",
                        to="core.climatecondition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de Germinación",
                "verbose_name_plural": "Configuraciones de Germinación",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="germinationrecord",
            name="germination_condition",
        ),
        migrations.DeleteModel(
            name="GerminationCondition",
        ),
        migrations.AddField(
            model_name="germinationrecord",
            name="germination_setup",
            field=models.ForeignKey(
                blank=True,
                help_text="Configuración de germinación utilizada",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="germination_records",
                to="germination.germinationsetup",
            ),
        ),
    ]
