# Generated by Django 4.2.7 on 2025-09-27 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha de creación del registro"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Fecha de última actualización del registro",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("pollination", "Reporte de Polinización"),
                            ("germination", "Reporte de Germinación"),
                            ("statistical", "Reporte Estadístico"),
                        ],
                        help_text="Tipo de reporte",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Nombre para mostrar del tipo de reporte",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descripción detallada del tipo de reporte",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si el tipo de reporte está activo",
                    ),
                ),
                (
                    "template_name",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del template para generar el reporte",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Reporte",
                "verbose_name_plural": "Tipos de Reporte",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha de creación del registro"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Fecha de última actualización del registro",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Título del reporte", max_length=200),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("generating", "Generando"),
                            ("completed", "Completado"),
                            ("failed", "Fallido"),
                        ],
                        default="pending",
                        help_text="Estado del reporte",
                        max_length=20,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("excel", "Excel"), ("json", "JSON")],
                        default="pdf",
                        help_text="Formato del reporte",
                        max_length=10,
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        default=dict,
                        help_text="Parámetros utilizados para generar el reporte",
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        help_text="Ruta del archivo generado",
                        max_length=500,
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, help_text="Tamaño del archivo en bytes", null=True
                    ),
                ),
                (
                    "generation_started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha y hora de inicio de generación",
                        null=True,
                    ),
                ),
                (
                    "generation_completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha y hora de finalización de generación",
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Mensaje de error si la generación falló"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict, help_text="Metadatos adicionales del reporte"
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        help_text="Usuario que generó el reporte",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report_type",
                    models.ForeignKey(
                        help_text="Tipo de reporte",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="reports.reporttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte",
                "verbose_name_plural": "Reportes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["report_type", "status"],
                        name="reports_rep_report__a78a12_idx",
                    ),
                    models.Index(
                        fields=["generated_by", "created_at"],
                        name="reports_rep_generat_b60f00_idx",
                    ),
                ],
            },
        ),
    ]
