# Generated by Django 4.2.7 on 2025-09-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="metadata",
            field=models.JSONField(
                blank=True, default=dict, help_text="Metadatos adicionales del reporte"
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="parameters",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Parámetros utilizados para generar el reporte",
            ),
        ),
    ]
