# Generated by Django 4.2.7 on 2025-09-27 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("germination", "0001_initial"),
        ("pollination", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha de creación del registro"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Fecha de última actualización del registro",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("semanal", "Semanal"),
                            ("preventiva", "Preventiva"),
                            ("frecuente", "Frecuente"),
                        ],
                        help_text="Tipo de alerta en el sistema",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Descripción detallada del tipo de alerta"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si el tipo de alerta está activo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Alerta",
                "verbose_name_plural": "Tipos de Alerta",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha de creación del registro"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Fecha de última actualización del registro",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Título de la alerta", max_length=200),
                ),
                (
                    "message",
                    models.TextField(help_text="Mensaje detallado de la alerta"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("read", "Leída"),
                            ("dismissed", "Descartada"),
                        ],
                        default="pending",
                        help_text="Estado actual de la alerta",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Baja"),
                            ("medium", "Media"),
                            ("high", "Alta"),
                            ("urgent", "Urgente"),
                        ],
                        default="medium",
                        help_text="Prioridad de la alerta",
                        max_length=20,
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateTimeField(
                        help_text="Fecha programada para mostrar la alerta"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha de expiración de la alerta",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Metadatos adicionales de la alerta en formato JSON",
                    ),
                ),
                (
                    "alert_type",
                    models.ForeignKey(
                        help_text="Tipo de alerta",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="alerts.alerttype",
                    ),
                ),
                (
                    "germination_record",
                    models.ForeignKey(
                        blank=True,
                        help_text="Registro de germinación relacionado",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="germination.germinationrecord",
                    ),
                ),
                (
                    "pollination_record",
                    models.ForeignKey(
                        blank=True,
                        help_text="Registro de polinización relacionado",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="pollination.pollinationrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerta",
                "verbose_name_plural": "Alertas",
                "ordering": ["-scheduled_date", "-priority"],
            },
        ),
        migrations.CreateModel(
            name="UserAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha de creación del registro"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Fecha de última actualización del registro",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si el usuario ha leído la alerta",
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha y hora en que se leyó la alerta",
                        null=True,
                    ),
                ),
                (
                    "is_dismissed",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si el usuario ha descartado la alerta",
                    ),
                ),
                (
                    "dismissed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha y hora en que se descartó la alerta",
                        null=True,
                    ),
                ),
                (
                    "alert",
                    models.ForeignKey(
                        help_text="Alerta asignada al usuario",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_alerts",
                        to="alerts.alert",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Usuario que recibe la alerta",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerta de Usuario",
                "verbose_name_plural": "Alertas de Usuario",
                "ordering": ["-alert__scheduled_date"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read"],
                        name="alerts_user_user_id_ecb337_idx",
                    ),
                    models.Index(
                        fields=["user", "is_dismissed"],
                        name="alerts_user_user_id_ad387e_idx",
                    ),
                ],
                "unique_together": {("user", "alert")},
            },
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["status", "scheduled_date"],
                name="alerts_aler_status_adcdc1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["alert_type", "status"], name="alerts_aler_alert_t_017623_idx"
            ),
        ),
    ]
