# Generated by Django 4.2.7 on 2025-09-27 06:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClimateCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha de creación del registro"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Fecha de última actualización del registro",
                    ),
                ),
                (
                    "weather",
                    models.CharField(
                        choices=[
                            ("Soleado", "Soleado"),
                            ("Nublado", "Nublado"),
                            ("Lluvioso", "Lluvioso"),
                            ("Parcialmente nublado", "Parcialmente nublado"),
                        ],
                        help_text="Condición climática durante la polinización",
                        max_length=50,
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Temperatura en grados Celsius",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "humidity",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Humedad relativa en porcentaje (0-100)",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "wind_speed",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Velocidad del viento en km/h",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Observaciones adicionales sobre las condiciones climáticas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Condición Climática",
                "verbose_name_plural": "Condiciones Climáticas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha de creación del registro"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Fecha de última actualización del registro",
                    ),
                ),
                (
                    "genus",
                    models.CharField(
                        help_text="Género botánico de la planta", max_length=100
                    ),
                ),
                (
                    "species",
                    models.CharField(
                        help_text="Especie botánica de la planta", max_length=100
                    ),
                ),
                (
                    "vivero",
                    models.CharField(
                        help_text="Nombre del vivero donde se encuentra la planta",
                        max_length=100,
                    ),
                ),
                (
                    "mesa",
                    models.CharField(
                        help_text="Mesa o sección dentro del vivero", max_length=50
                    ),
                ),
                (
                    "pared",
                    models.CharField(
                        help_text="Pared o ubicación específica en la mesa",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si la planta está activa en el sistema",
                    ),
                ),
            ],
            options={
                "verbose_name": "Planta",
                "verbose_name_plural": "Plantas",
                "ordering": ["genus", "species", "vivero", "mesa", "pared"],
                "unique_together": {("genus", "species", "vivero", "mesa", "pared")},
            },
        ),
        migrations.CreateModel(
            name="PollinationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha de creación del registro"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Fecha de última actualización del registro",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Self", "Autopolinización"),
                            ("Sibling", "Polinización entre hermanos"),
                            ("Híbrido", "Hibridación"),
                        ],
                        help_text="Tipo de polinización",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Descripción detallada del tipo de polinización"
                    ),
                ),
                (
                    "requires_father_plant",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si este tipo requiere planta padre",
                    ),
                ),
                (
                    "allows_different_species",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si permite especies diferentes entre plantas",
                    ),
                ),
                (
                    "maturation_days",
                    models.PositiveIntegerField(
                        default=120,
                        help_text="Días estimados para maduración de cápsulas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Polinización",
                "verbose_name_plural": "Tipos de Polinización",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PollinationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha de creación del registro"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Fecha de última actualización del registro",
                    ),
                ),
                (
                    "pollination_date",
                    models.DateField(
                        help_text="Fecha en que se realizó la polinización"
                    ),
                ),
                (
                    "estimated_maturation_date",
                    models.DateField(
                        blank=True,
                        help_text="Fecha estimada de maduración de cápsulas (calculada automáticamente)",
                        null=True,
                    ),
                ),
                (
                    "capsules_quantity",
                    models.PositiveIntegerField(
                        help_text="Cantidad de cápsulas polinizadas",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "observations",
                    models.TextField(
                        blank=True,
                        help_text="Observaciones adicionales sobre la polinización",
                    ),
                ),
                (
                    "is_successful",
                    models.BooleanField(
                        blank=True,
                        help_text="Indica si la polinización fue exitosa (se determina posteriormente)",
                        null=True,
                    ),
                ),
                (
                    "maturation_confirmed",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si se confirmó la maduración de las cápsulas",
                    ),
                ),
                (
                    "maturation_confirmed_date",
                    models.DateField(
                        blank=True,
                        help_text="Fecha en que se confirmó la maduración",
                        null=True,
                    ),
                ),
                (
                    "climate_condition",
                    models.ForeignKey(
                        help_text="Condiciones climáticas durante la polinización",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pollination_records",
                        to="pollination.climatecondition",
                    ),
                ),
                (
                    "father_plant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Planta padre (donadora del polen) - requerida para Sibling e Híbrido",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="as_father_plant",
                        to="pollination.plant",
                    ),
                ),
                (
                    "mother_plant",
                    models.ForeignKey(
                        help_text="Planta madre (receptora del polen)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="as_mother_plant",
                        to="pollination.plant",
                    ),
                ),
                (
                    "new_plant",
                    models.ForeignKey(
                        help_text="Nueva planta resultante de la polinización",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="as_new_plant",
                        to="pollination.plant",
                    ),
                ),
                (
                    "pollination_type",
                    models.ForeignKey(
                        help_text="Tipo de polinización realizada",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pollination_records",
                        to="pollination.pollinationtype",
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        help_text="Usuario responsable de la polinización",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pollination_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Polinización",
                "verbose_name_plural": "Registros de Polinización",
                "ordering": ["-pollination_date", "-created_at"],
            },
        ),
    ]
