# Generated by Django 4.2.7 on 2025-10-20 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("pollination", "0002_update_climate_condition_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pollinationrecord",
            name="climate_condition",
            field=models.ForeignKey(
                help_text="Condiciones climáticas durante la polinización",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pollination_records",
                to="core.climatecondition",
            ),
        ),
        migrations.DeleteModel(
            name="ClimateCondition",
        ),
    ]
